services:
  frontend:
    build:
      context: .
      target: dev
    container_name: library_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:4000/graphql
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev --hostname 0.0.0.0 --port 3000
